site_name: "Capfinder"
repo_url: https://github.com/adnaniazi/capfinder

theme:
  name: material
  features:
    - content.code.copy
    - content.tabs.link
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

nav:
  - Introduction: 'index.md'
  - Installation: 'installation.md'
  - Usage:
      - 0. Graphical overview: 'usage_overview.md'
      - 1. mRNA Sample Preparation: 'mRNA_sample_prep.md'
      - 2. Data Preparation: 'preprocessing.md'
      - 3. Cap Prediction: 'prediction.md'
  - Training for New Caps:
          - 0. Graphical overview: 'training_overview.md'
          - 1. Designing Cap Oligo: 'oligo_design.md'
          - 2. Sequencing and Basecalling: 'sequencing_and_basecalling.md'
          - 3. Extending Cap Mapping: 'extend_capmap.md'
          - 4. Extracting Cap Signal: 'extract_train_signal.md'
          - 5. Making Training Data: 'all_caps_data.md'
          - 6. Training Capfinder: 'training.md'
          - 7. Using Custom Trained Model: 'using_custom_model.md'
  - Updating Capfinder: 'updating.md'
  - Developer Guide: 'development_setup.md'
  - Using Capfinder's Python API: 'python_api.md'
  - API Documentation: api_docs.md
  - Change Log: changelog.md
  - Our Contributors: 'contributions.md'

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.snippets:
      check_paths: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde

plugins:
  - search:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_signature_annotations: true
            show_source: true
            show_submodules: true
