site_name: "Capfinder"
repo_url: https://github.com/adnaniazi/capfinder



theme:
  name: material
  features:
    - content.code.copy
    - content.tabs.link
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

nav:
  - Introduction: 'index.md'
  - Installation: 'installation.md'
  - Usage:
      - Data Preparation: 'preprocessing.md'
      - Cap Prediction: 'prediction.md'
  - Updating Capfinder: 'updating.md'
  - Developer guide: 'development.md'
  - API Documentation: api_docs.md
  - Change Log: changelog.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.snippets:
      check_paths: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true


plugins:
  - search:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_signature_annotations: true
            show_source: true
            show_submodules: true
