# Generated by CodiumAI
from capfinder.visualize_alns import calculate_average_quality


class TestCalculateAverageQuality:
    # Calculate average quality score for a read with all quality scores equal
    def test_all_quality_scores_equal(self) -> None:
        quality_scores = [30, 30, 30, 30, 30]
        result = calculate_average_quality(quality_scores)
        assert result == 30.0

    # Calculate average quality score for a read with minimum possible quality score
    def test_minimum_quality_score(self) -> None:
        quality_scores = [0]
        result = calculate_average_quality(quality_scores)
        assert result == 0.0
